stages:
  - build
  - deployToAwsInLegado

build:
  image: docker
  only:
    - master
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:testLaboratory" .
    - docker push "$CI_REGISTRY_IMAGE:testLaboratory"

deployToAwsInLegado:
  stage: deployToAwsInLegado
  image: alpine
  variables:
    SERVER: $SERVER_IP
    PORT: $SERVER_PORT
  only:
    - master
  script:
    - apk add openssh
    - apk add bash
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS_AWS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY_AWS")'
    - scp $ENV ubuntu@$SERVER:.envtestLaboratory
    # log into Docker registry
    - ssh ubuntu@$SERVER "echo $CI_BUILD_TOKEN | docker login --username gitlab-ci-token --password-stdin registry.gitlab.com"
    # stop container, remove image.
    - ssh ubuntu@$SERVER "docker container stop testLaboratory" || true
    - ssh ubuntu@$SERVER "docker container rm testLaboratory" || true
    - ssh ubuntu@$SERVER "docker image rm ${CI_REGISTRY_IMAGE}:testLaboratory" || true
    # start new container
    - ssh ubuntu@$SERVER "docker container run -v /home/ubuntu/.envtestLaboratory:/app/.env --name testLaboratory -p $PORT:3344 -d ${CI_REGISTRY_IMAGE}:testLaboratory"
