version: "3.5"

services:

  app:
    build: .
    container_name: laboratory_api
    volumes:
      - ./:/app
    ports:
      - ${PORT}:3344
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: laboratory_database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
